CREATE TABLE CUSTOMERS(
    ID INT UNSIGNED NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(150) NOT NULL,
    IRSID VARCHAR(25),
    PHONE VARCHAR(25),
    FOREIGN KEY(ID) REFERENCES USERS(ID)
);
