CREATE TABLE ORDERS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(25) NOT NULL,
    STATUS VARCHAR(25) NOT NULL,
    CUSTOMERID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID), 
    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMERS(ID)
);
