CREATE TABLE ORDERS_CONTENT(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ORDERID INT UNSIGNED NOT NULL,
    PRODUCTID INT UNSIGNED NOT NULL,
    AMOUNT INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID)
);
